package entity

import (
	context "context"
	fmt "fmt"
	gorm1 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm "github.com/jinzhu/gorm"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	strings "strings"
	time "time"
)

type AccessTokenEntityORM struct {
	CreatedAt *time.Time
	ExpiresAt *time.Time `gorm:"not null"`
	Id        string     `gorm:"type:uuid;primary_key;default:uuid_generate_v4();not null"`
	Revoked   bool       `gorm:"default:0"`
	UpdatedAt *time.Time
	Users     []*UserEntityORM `gorm:"foreignkey:AccessTokenEntityId;association_foreignkey:Id"`
}

// TableName overrides the default tablename generated by GORM
func (AccessTokenEntityORM) TableName() string {
	return "access_tokens"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *AccessTokenEntity) ToORM(ctx context.Context) (AccessTokenEntityORM, error) {
	to := AccessTokenEntityORM{}
	var err error
	if prehook, ok := interface{}(m).(AccessTokenEntityWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Id = m.Id
	for _, v := range m.Users {
		if v != nil {
			if tempUsers, cErr := v.ToORM(ctx); cErr == nil {
				to.Users = append(to.Users, &tempUsers)
			} else {
				return to, cErr
			}
		} else {
			to.Users = append(to.Users, nil)
		}
	}
	to.Revoked = m.Revoked
	if m.ExpiresAt != nil {
		t := m.ExpiresAt.AsTime()
		to.ExpiresAt = &t
	}
	if m.CreatedAt != nil {
		t := m.CreatedAt.AsTime()
		to.CreatedAt = &t
	}
	if m.UpdatedAt != nil {
		t := m.UpdatedAt.AsTime()
		to.UpdatedAt = &t
	}
	if posthook, ok := interface{}(m).(AccessTokenEntityWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *AccessTokenEntityORM) ToPB(ctx context.Context) (AccessTokenEntity, error) {
	to := AccessTokenEntity{}
	var err error
	if prehook, ok := interface{}(m).(AccessTokenEntityWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Id = m.Id
	for _, v := range m.Users {
		if v != nil {
			if tempUsers, cErr := v.ToPB(ctx); cErr == nil {
				to.Users = append(to.Users, &tempUsers)
			} else {
				return to, cErr
			}
		} else {
			to.Users = append(to.Users, nil)
		}
	}
	to.Revoked = m.Revoked
	if m.ExpiresAt != nil {
		to.ExpiresAt = timestamppb.New(*m.ExpiresAt)
	}
	if m.CreatedAt != nil {
		to.CreatedAt = timestamppb.New(*m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		to.UpdatedAt = timestamppb.New(*m.UpdatedAt)
	}
	if posthook, ok := interface{}(m).(AccessTokenEntityWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type AccessTokenEntity the arg will be the target, the caller the one being converted from

// AccessTokenEntityBeforeToORM called before default ToORM code
type AccessTokenEntityWithBeforeToORM interface {
	BeforeToORM(context.Context, *AccessTokenEntityORM) error
}

// AccessTokenEntityAfterToORM called after default ToORM code
type AccessTokenEntityWithAfterToORM interface {
	AfterToORM(context.Context, *AccessTokenEntityORM) error
}

// AccessTokenEntityBeforeToPB called before default ToPB code
type AccessTokenEntityWithBeforeToPB interface {
	BeforeToPB(context.Context, *AccessTokenEntity) error
}

// AccessTokenEntityAfterToPB called after default ToPB code
type AccessTokenEntityWithAfterToPB interface {
	AfterToPB(context.Context, *AccessTokenEntity) error
}

// DefaultCreateAccessTokenEntity executes a basic gorm create call
func DefaultCreateAccessTokenEntity(ctx context.Context, in *AccessTokenEntity, db *gorm.DB) (*AccessTokenEntity, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type AccessTokenEntityORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm.DB) error
}

func DefaultReadAccessTokenEntity(ctx context.Context, in *AccessTokenEntity, db *gorm.DB) (*AccessTokenEntity, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if ormObj.Id == "" {
		return nil, errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithBeforeReadApplyQuery); ok {
		if db, err = hook.BeforeReadApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if db, err = gorm1.ApplyFieldSelection(ctx, db, nil, &AccessTokenEntityORM{}); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithBeforeReadFind); ok {
		if db, err = hook.BeforeReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	ormResponse := AccessTokenEntityORM{}
	if err = db.Where(&ormObj).First(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormResponse).(AccessTokenEntityORMWithAfterReadFind); ok {
		if err = hook.AfterReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormResponse.ToPB(ctx)
	return &pbResponse, err
}

type AccessTokenEntityORMWithBeforeReadApplyQuery interface {
	BeforeReadApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityORMWithBeforeReadFind interface {
	BeforeReadFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityORMWithAfterReadFind interface {
	AfterReadFind(context.Context, *gorm.DB) error
}

func DefaultDeleteAccessTokenEntity(ctx context.Context, in *AccessTokenEntity, db *gorm.DB) error {
	if in == nil {
		return errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return err
	}
	if ormObj.Id == "" {
		return errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithBeforeDelete_); ok {
		if db, err = hook.BeforeDelete_(ctx, db); err != nil {
			return err
		}
	}
	err = db.Where(&ormObj).Delete(&AccessTokenEntityORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithAfterDelete_); ok {
		err = hook.AfterDelete_(ctx, db)
	}
	return err
}

type AccessTokenEntityORMWithBeforeDelete_ interface {
	BeforeDelete_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityORMWithAfterDelete_ interface {
	AfterDelete_(context.Context, *gorm.DB) error
}

func DefaultDeleteAccessTokenEntitySet(ctx context.Context, in []*AccessTokenEntity, db *gorm.DB) error {
	if in == nil {
		return errors.NilArgumentError
	}
	var err error
	keys := []string{}
	for _, obj := range in {
		ormObj, err := obj.ToORM(ctx)
		if err != nil {
			return err
		}
		if ormObj.Id == "" {
			return errors.EmptyIdError
		}
		keys = append(keys, ormObj.Id)
	}
	if hook, ok := (interface{}(&AccessTokenEntityORM{})).(AccessTokenEntityORMWithBeforeDeleteSet); ok {
		if db, err = hook.BeforeDeleteSet(ctx, in, db); err != nil {
			return err
		}
	}
	err = db.Where("id in (?)", keys).Delete(&AccessTokenEntityORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := (interface{}(&AccessTokenEntityORM{})).(AccessTokenEntityORMWithAfterDeleteSet); ok {
		err = hook.AfterDeleteSet(ctx, in, db)
	}
	return err
}

type AccessTokenEntityORMWithBeforeDeleteSet interface {
	BeforeDeleteSet(context.Context, []*AccessTokenEntity, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityORMWithAfterDeleteSet interface {
	AfterDeleteSet(context.Context, []*AccessTokenEntity, *gorm.DB) error
}

// DefaultStrictUpdateAccessTokenEntity clears / replaces / appends first level 1:many children and then executes a gorm update call
func DefaultStrictUpdateAccessTokenEntity(ctx context.Context, in *AccessTokenEntity, db *gorm.DB) (*AccessTokenEntity, error) {
	if in == nil {
		return nil, fmt.Errorf("Nil argument to DefaultStrictUpdateAccessTokenEntity")
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	lockedRow := &AccessTokenEntityORM{}
	db.Model(&ormObj).Set("gorm:query_option", "FOR UPDATE").Where("id=?", ormObj.Id).First(lockedRow)
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithBeforeStrictUpdateCleanup); ok {
		if db, err = hook.BeforeStrictUpdateCleanup(ctx, db); err != nil {
			return nil, err
		}
	}
	filterUsers := UserEntityORM{}
	if ormObj.Id == "" {
		return nil, errors.EmptyIdError
	}
	filterUsers.AccessTokenEntityId = new(string)
	*filterUsers.AccessTokenEntityId = ormObj.Id
	if err = db.Where(filterUsers).Delete(UserEntityORM{}).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithBeforeStrictUpdateSave); ok {
		if db, err = hook.BeforeStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Save(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithAfterStrictUpdateSave); ok {
		if err = hook.AfterStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	if err != nil {
		return nil, err
	}
	return &pbResponse, err
}

type AccessTokenEntityORMWithBeforeStrictUpdateCleanup interface {
	BeforeStrictUpdateCleanup(context.Context, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityORMWithBeforeStrictUpdateSave interface {
	BeforeStrictUpdateSave(context.Context, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityORMWithAfterStrictUpdateSave interface {
	AfterStrictUpdateSave(context.Context, *gorm.DB) error
}

// DefaultPatchAccessTokenEntity executes a basic gorm update call with patch behavior
func DefaultPatchAccessTokenEntity(ctx context.Context, in *AccessTokenEntity, updateMask *field_mask.FieldMask, db *gorm.DB) (*AccessTokenEntity, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	var pbObj AccessTokenEntity
	var err error
	if hook, ok := interface{}(&pbObj).(AccessTokenEntityWithBeforePatchRead); ok {
		if db, err = hook.BeforePatchRead(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbReadRes, err := DefaultReadAccessTokenEntity(ctx, &AccessTokenEntity{Id: in.GetId()}, db)
	if err != nil {
		return nil, err
	}
	pbObj = *pbReadRes
	if hook, ok := interface{}(&pbObj).(AccessTokenEntityWithBeforePatchApplyFieldMask); ok {
		if db, err = hook.BeforePatchApplyFieldMask(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	if _, err := DefaultApplyFieldMaskAccessTokenEntity(ctx, &pbObj, in, updateMask, "", db); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&pbObj).(AccessTokenEntityWithBeforePatchSave); ok {
		if db, err = hook.BeforePatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := DefaultStrictUpdateAccessTokenEntity(ctx, &pbObj, db)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(pbResponse).(AccessTokenEntityWithAfterPatchSave); ok {
		if err = hook.AfterPatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	return pbResponse, nil
}

type AccessTokenEntityWithBeforePatchRead interface {
	BeforePatchRead(context.Context, *AccessTokenEntity, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityWithBeforePatchApplyFieldMask interface {
	BeforePatchApplyFieldMask(context.Context, *AccessTokenEntity, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityWithBeforePatchSave interface {
	BeforePatchSave(context.Context, *AccessTokenEntity, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityWithAfterPatchSave interface {
	AfterPatchSave(context.Context, *AccessTokenEntity, *field_mask.FieldMask, *gorm.DB) error
}

// DefaultPatchSetAccessTokenEntity executes a bulk gorm update call with patch behavior
func DefaultPatchSetAccessTokenEntity(ctx context.Context, objects []*AccessTokenEntity, updateMasks []*field_mask.FieldMask, db *gorm.DB) ([]*AccessTokenEntity, error) {
	if len(objects) != len(updateMasks) {
		return nil, fmt.Errorf(errors.BadRepeatedFieldMaskTpl, len(updateMasks), len(objects))
	}

	results := make([]*AccessTokenEntity, 0, len(objects))
	for i, patcher := range objects {
		pbResponse, err := DefaultPatchAccessTokenEntity(ctx, patcher, updateMasks[i], db)
		if err != nil {
			return nil, err
		}

		results = append(results, pbResponse)
	}

	return results, nil
}

// DefaultApplyFieldMaskAccessTokenEntity patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskAccessTokenEntity(ctx context.Context, patchee *AccessTokenEntity, patcher *AccessTokenEntity, updateMask *field_mask.FieldMask, prefix string, db *gorm.DB) (*AccessTokenEntity, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors.NilArgumentError
	}
	var err error
	var updatedExpiresAt bool
	var updatedCreatedAt bool
	var updatedUpdatedAt bool
	for i, f := range updateMask.Paths {
		if f == prefix+"Id" {
			patchee.Id = patcher.Id
			continue
		}
		if f == prefix+"Users" {
			patchee.Users = patcher.Users
			continue
		}
		if f == prefix+"Revoked" {
			patchee.Revoked = patcher.Revoked
			continue
		}
		if !updatedExpiresAt && strings.HasPrefix(f, prefix+"ExpiresAt.") {
			if patcher.ExpiresAt == nil {
				patchee.ExpiresAt = nil
				continue
			}
			if patchee.ExpiresAt == nil {
				patchee.ExpiresAt = &timestamppb.Timestamp{}
			}
			childMask := &field_mask.FieldMask{}
			for j := i; j < len(updateMask.Paths); j++ {
				if trimPath := strings.TrimPrefix(updateMask.Paths[j], prefix+"ExpiresAt."); trimPath != updateMask.Paths[j] {
					childMask.Paths = append(childMask.Paths, trimPath)
				}
			}
			if err := gorm1.MergeWithMask(patcher.ExpiresAt, patchee.ExpiresAt, childMask); err != nil {
				return nil, nil
			}
		}
		if f == prefix+"ExpiresAt" {
			updatedExpiresAt = true
			patchee.ExpiresAt = patcher.ExpiresAt
			continue
		}
		if !updatedCreatedAt && strings.HasPrefix(f, prefix+"CreatedAt.") {
			if patcher.CreatedAt == nil {
				patchee.CreatedAt = nil
				continue
			}
			if patchee.CreatedAt == nil {
				patchee.CreatedAt = &timestamppb.Timestamp{}
			}
			childMask := &field_mask.FieldMask{}
			for j := i; j < len(updateMask.Paths); j++ {
				if trimPath := strings.TrimPrefix(updateMask.Paths[j], prefix+"CreatedAt."); trimPath != updateMask.Paths[j] {
					childMask.Paths = append(childMask.Paths, trimPath)
				}
			}
			if err := gorm1.MergeWithMask(patcher.CreatedAt, patchee.CreatedAt, childMask); err != nil {
				return nil, nil
			}
		}
		if f == prefix+"CreatedAt" {
			updatedCreatedAt = true
			patchee.CreatedAt = patcher.CreatedAt
			continue
		}
		if !updatedUpdatedAt && strings.HasPrefix(f, prefix+"UpdatedAt.") {
			if patcher.UpdatedAt == nil {
				patchee.UpdatedAt = nil
				continue
			}
			if patchee.UpdatedAt == nil {
				patchee.UpdatedAt = &timestamppb.Timestamp{}
			}
			childMask := &field_mask.FieldMask{}
			for j := i; j < len(updateMask.Paths); j++ {
				if trimPath := strings.TrimPrefix(updateMask.Paths[j], prefix+"UpdatedAt."); trimPath != updateMask.Paths[j] {
					childMask.Paths = append(childMask.Paths, trimPath)
				}
			}
			if err := gorm1.MergeWithMask(patcher.UpdatedAt, patchee.UpdatedAt, childMask); err != nil {
				return nil, nil
			}
		}
		if f == prefix+"UpdatedAt" {
			updatedUpdatedAt = true
			patchee.UpdatedAt = patcher.UpdatedAt
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListAccessTokenEntity executes a gorm list call
func DefaultListAccessTokenEntity(ctx context.Context, db *gorm.DB) ([]*AccessTokenEntity, error) {
	in := AccessTokenEntity{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm1.ApplyCollectionOperators(ctx, db, &AccessTokenEntityORM{}, &AccessTokenEntity{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("id")
	ormResponse := []AccessTokenEntityORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AccessTokenEntityORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*AccessTokenEntity{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type AccessTokenEntityORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type AccessTokenEntityORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm.DB, *[]AccessTokenEntityORM) error
}
